#!/bin/bash
set -e
echo "Starting.."

echo "=====> Loading bash profile..."
. /home/work/.bashrc

# execute rest as root
exec sudo -E -u root /bin/sh - <<EOF
#  change ownership
echo "Changing ownership..."
chown -R root:root /work/tools

# prevent "bad interpreter: Text file busy"
echo "Syncing..."
sync

echo "Running the build..."
sh /sbin/docker-build-with-tools /work
EOF
